#version 450
#extension GL_EXT_debug_printf : enable

layout(set = 0, binding = 1, std430) buffer results { uint result[]; };
layout(set = 0, binding = 0, std430) buffer values { uint value[]; };

void main(){
    // Square the input
    const uint id = gl_GlobalInvocationID.x;
    const uint value = value[id];
    debugPrintfEXT("Thread %i; value = %i\n", id, value);
    result[id] = (value * value);
}
